#!/bin/bash
source /opt/ros/humble/setup.bash
if [ -f $HOME/ros2_ws/install/setup.bash ]; then
    source $HOME/ros2_ws/install/setup.bash
fi
ros2 launch mecanum4_description sim_bringup.launch.py "$@"
