#!/bin/bash

# Source ROS 2 Humble
source /opt/ros/humble/setup.bash

# Source the workspace
if [ -f ~/ros2_ws/install/setup.bash ]; then
    source ~/ros2_ws/install/setup.bash
fi

# Run the navigation amcl bringup with NVIDIA GPU offload
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia ros2 launch mecanum4_description nav2_amcl_bringup.launch.py "$@"
